### ISSUE TITLE
sql2json does not support INSERT INTO ... VALUES(a,b), (c,d) syntax #11 by galz was closed on Aug 30 2016 

### ISSUE THREAD

**Issue by Idafe** [martindrapeau/csvjson-app#17] opened 2017-05-03 19:55 UTC
http://www.csvjson.com/sql2json/4ab2f3433f4f6a320988ee11b8f9428e

Same problem. 
sql2json does not support INSERT INTO ... VALUES(a,b), (c,d) syntax
#11 by galz was closed on Aug 30 2016 

You could tell me how to add low commas without the app separating them like fields. The link that you put to solve the issue 11, the save state is not operative.

Thank you very much for your application.

**Comment by martindrapeau** [comment] 2017-12-14 02:07
Duplicate of #25 and fixed.

**Closed by martindrapeau** 2017-12-14 02:07 UTC
